config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies, only: :show do
    resources :rides
    resource :customer_sign_up, path: "customers", only: %i[create new]
    resource :session
  end
  namespace :dashboard do
    resources :employees
    resources :companies
      resources :service_areas
      resources :rides
  end
  namespace :admin do
    resources :organizations
  end
  get "dashboard/index"
  resource :session
  resource :sign_up
  resources :passwords, param: :token
  resources :customers, only: :show
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard/companies#index"
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  include Caber::Object

  belongs_to :organization
  has_many :company_employees, dependent: :destroy, inverse_of: :company
  has_many :employees, -> { select("employees.*, company_employees.role as role") }, through: :company_employees
end

app/models/company_employee.rb
# frozen_string_literal: true

class CompanyEmployee < ApplicationRecord
  belongs_to :company, inverse_of: :company_employees
  belongs_to :employee, inverse_of: :company_employees

  enum :role, { driver: 0, customer_support: 1, manager: 2, admin: 3, owner: 4 }
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :session
  attribute :company
  attribute :organization
  delegate :user, to: :session, allow_nil: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  include Authenticateable
  include Caber::Subject
  include Caber::Object

  belongs_to :company
  has_many :rides, dependent: :nullify
  # has_one :acquisition_area, -> { rides.completed.first.service_area }
  # has_one :acquisition_company, -> { rides.completed.first.company }
end

app/models/dashboard.rb
# frozen_string_literal: true

module Dashboard
  def self.table_name_prefix
    "dashboard_"
  end
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  include Authenticateable
  include Caber::Subject
  include Caber::Object

  has_many :company_employees, dependent: :destroy, inverse_of: :employee
  has_many :companies, -> { select("companies.*, company_employees.role as role") }, through: :company_employees
  has_many :rides, inverse_of: :driver, dependent: :nullify

  accepts_nested_attributes_for :company_employees, allow_destroy: true

  def not_associated_companies
    if user.nil?
      Current.organization.companies
    else
      user.organization.companies.where.not(id: companies.pluck(:id))
    end
  end
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  include Caber::Object
  has_many :companies
end

app/models/ride.rb
# frozen_string_literal: true

class Ride < ApplicationRecord
  belongs_to :customer
  belongs_to :company
  belongs_to :driver, class_name: "Employee", optional: true
end

app/models/service_area.rb
# frozen_string_literal: true

class ServiceArea < ApplicationRecord
  belongs_to :company

  enum :status, { inactive: 0, active: 1 }
end

app/models/session.rb
# frozen_string_literal: true

class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  belongs_to :organization

  delegated_type :authenticateable, types: %w[Employee Customer]
  validates_associated :authenticateable
  accepts_nested_attributes_for :authenticateable

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/customer_sign_ups_controller.rb
# frozen_string_literal: true

class CustomerSignUpsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  #  rate_limit to: 1, within: 3.minutes, only: :create, with: lambda {
  # redirect_to new_sign_up_url, alert: "Try again later."
  #  }
  def new; end

  def create
    @user = User.new(user_params)
    @user.organization = @company.organization
    @user.authenticateable = Customer.new(company: @company)
    @user.save!

    if (user = User.authenticate_by(user_params))
      start_new_session_for user
      redirect_to company_url(@company)
    end
  end

  private

  def user_params
    params.expect(user: %i[email_address password password_confirmation])
  end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/helpers/customer_sign_ups_helper.rb
# frozen_string_literal: true

module CustomerSignUpsHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/rides_helper.rb
# frozen_string_literal: true

module RidesHelper
end

app/helpers/sign_ups_helper.rb
# frozen_string_literal: true

module SignUpsHelper
end

app/views/customer_sign_ups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <% if alert = flash[:alert] %>
    <p
      class="
        py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block
      "
      id="alert"
    ><%= alert %></p>
  <% end %>

  <% if notice = flash[:notice] %>
    <p
      class="
        py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block
      "
      id="notice"
    ><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Sign Up</h1>

  <%= form_with url: company_customer_sign_up_url(@company), class: "contents" do |form| %>
    <%= fields_for :user do |user_fields| %>
      <div class="my-5">
        <%= user_fields.email_field :email_address,
                                required: true,
                                autofocus: true,
                                autocomplete: "username",
                                placeholder: "Enter your email address",
                                value: params[:email_address],
                                class:
                                  "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= user_fields.password_field :password,
                                   required: true,
                                   autocomplete: "password",
                                   placeholder: "Enter your password",
                                   maxlength: 72,
                                   class:
                                     "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
    <% end %>

    <div class="col-span-6 sm:flex sm:items-center sm:gap-4">
      <div class="inline">
        <%= form.submit "Sign Up",
                    class:
                      "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>