config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies, only: :show do
    resources :rides
    resource :customer_sign_up, path: "customers", only: %i[create new]
    resource :session
  end
  namespace :dashboard do
    resources :employees
    resources :companies
      resources :service_areas
      resources :rides
  end
  namespace :admin do
    resources :organizations
  end
  get "dashboard/index"
  resource :session
  resource :sign_up
  resources :passwords, param: :token
  resources :customers, only: :show
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard/companies#index"
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  include Caber::Object

  belongs_to :organization
  has_many :company_employees, dependent: :destroy, inverse_of: :company
  has_many :employees, -> { select("employees.*, company_employees.role as role") }, through: :company_employees
end

app/models/dashboard.rb
# frozen_string_literal: true

module Dashboard
  def self.table_name_prefix
    "dashboard_"
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  allow_unauthenticated_access
  before_action :set_company, only: %i[ show ]
  def show; end

    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params.expect(:id))
    end
end

app/controllers/dashboard/companies_controller.rb
# frozen_string_literal: true

module Dashboard
  class CompaniesController < DashboardController
  before_action :set_organization
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /dashboard/companies or /dashboard/companies.json
  def index
    @companies = Current.organization.companies
  end

  # GET /dashboard/companies/1 or /dashboard/companies/1.json
  def show; end

  # GET /dashboard/companies/new
  def new
    @company = @organization.companies.new
  end

  # GET /dashboard/companies/1/edit
  def edit; end

  # POST /dashboard/companies or /dashboard/companies.json
  def create
    @company = @organization.companies.new(company_params)
    authorize @company, :create?

    respond_to do |format|
      if @company.save
        format.html { redirect_to [ :dashboard, @company ], notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboard/companies/1 or /dashboard/companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to [ :dashboard, @company ], notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/companies/1 or /dashboard/companies/1.json
  def destroy
    @company.destroy!

    respond_to do |format|
      format.html do
 redirect_to dashboard_companies_path, status: :see_other, notice: "Company was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params.expect(:id))
    end

    def set_organization
      @organization = Organization.first
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.expect(company: [ :name ])
    end
  end
end

app/controllers/dashboard/employees_controller.rb
# frozen_string_literal: true

module Dashboard
  class EmployeesController < DashboardController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /dashboard/employees or /dashboard/employees.json
  def index
    authorize(:employee)
    @employees = (Current.company || Current.organization).employees
  end

  # GET /dashboard/employees/1 or /dashboard/employees/1.json
  def show; end

  # GET /dashboard/employees/new
  def new
    # @employee = User.new(authenticateable: Employee.new).authenticateable
    @employee = Employee.new
  end

  # GET /dashboard/employees/1/edit
  def edit; end

  # POST /dashboard/employees or /dashboard/employees.json
  def create
    @user = User.new(user_params.merge(organization: Current.user.organization))
    @employee = Employee.new(employee_params)
    @employee.user = @user
    @user.authenticateable = @employee

    respond_to do |format|
      if @user.save
        format.html { redirect_to [ :dashboard, @employee ], notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors.merge(@user.errors), status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboard/employees/1 or /dashboard/employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        logger.debug "Updating employee #{@employee.company_employees.to_yaml}"
        format.html { redirect_to [ :dashboard, @employee ], notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/employees/1 or /dashboard/employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html do
 redirect_to dashboard_employees_path, status: :see_other, notice: "Employee was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: %i[email_address password])
    end

    def employee_params
      params.expect(employee: [ company_employees_attributes: [ %i[id company_id role _destroy] ] ])
    end
  end
end

app/controllers/dashboard/organizations_controller.rb
# frozen_string_literal: true

module Dashboard
  class OrganizationsController < DashboardController
  before_action :set_organization, only: %i[ show edit update destroy ]

  # GET /dashboard/organizations or /dashboard/organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /dashboard/organizations/1 or /dashboard/organizations/1.json
  def show; end

  # GET /dashboard/organizations/new
  def new
    @organization = Organization.new
  end

  # GET /dashboard/organizations/1/edit
  def edit; end

  # POST /dashboard/organizations or /dashboard/organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to [ :dashboard, @organization ], notice: "Organization was successfully created." }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboard/organizations/1 or /dashboard/organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to [ :dashboard, @organization ], notice: "Organization was successfully updated." }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/organizations/1 or /dashboard/organizations/1.json
  def destroy
    @organization.destroy!

    respond_to do |format|
      format.html do
 redirect_to dashboard_organizations_path, status: :see_other, notice: "Organization was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.expect(organization: [ :name ])
    end
  end
end

app/controllers/dashboard/service_areas_controller.rb
# frozen_string_literal: true

module Dashboard
  class ServiceAreasController < DashboardController
  before_action :set_service_area, only: %i[ show edit update destroy ]

  # GET /dashboard/service_areas or /dashboard/service_areas.json
  def index
    @service_areas = ServiceArea.all
  end

  # GET /dashboard/service_areas/1 or /dashboard/service_areas/1.json
  def show; end

  # GET /dashboard/service_areas/new
  def new
    @service_area = ServiceArea.new
  end

  # GET /dashboard/service_areas/1/edit
  def edit; end

  # POST /dashboard/service_areas or /dashboard/service_areas.json
  def create
    @service_area = ServiceArea.new(service_area_params)
    @service_area.company = Current.company

    respond_to do |format|
      if @service_area.save
        format.html { redirect_to [ :dashboard, @service_area ], notice: "Service area was successfully created." }
        format.json { render :show, status: :created, location: @service_area }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboard/service_areas/1 or /dashboard/service_areas/1.json
  def update
    respond_to do |format|
      if @service_area.update(service_area_params)
        format.html { redirect_to [ :dashboard, @service_area ], notice: "Service area was successfully updated." }
        format.json { render :show, status: :ok, location: @service_area }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/service_areas/1 or /dashboard/service_areas/1.json
  def destroy
    @service_area.destroy!

    respond_to do |format|
      format.html do
 redirect_to dashboard_service_areas_path, status: :see_other, notice: "Service area was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_service_area
      @service_area = ServiceArea.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def service_area_params
      params.expect(service_area: %i[name boundary status])
            .tap { |p| p[:boundary] = RGeo::GeoJSON.decode(p[:boundary]) }
    end
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class NavigationLink
  include ActiveModel::API

  attr_accessor :title, :controller, :url, :icon
end

class DashboardController < ApplicationController
  before_action :set_navigation
  before_action :set_company_and_organization

  def index; end

  private

  def set_company_and_organization
    Current.company ||= if session[:company_id]
                          Current.user.authenticateable.companies.find(session[:company_id])
                        else
                          Current.user.authenticateable.companies.first
                        end
    Current.organization ||= Current.company.organization
  end

  def set_navigation
    @navigation_links = [ {
      title: Company.name.pluralize,
      controller: "companies",
      url: dashboard_companies_path,
      icon: "fa-building"
    }, {
      title: Employee.name.pluralize,
      controller: "employees",
      url: dashboard_employees_path,
      icon: "fa-users"
    }, {
      title: ServiceArea.name.pluralize,
      controller: "service_areas",
      url: dashboard_service_areas_path,
      icon: "fa-earth-americas"
    } ].map { NavigationLink.new(it) }
  end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/helpers/dashboard/companies_helper.rb
# frozen_string_literal: true

module Dashboard
  module CompaniesHelper
  end
end

app/helpers/dashboard/employees_helper.rb
# frozen_string_literal: true

module Dashboard
  module EmployeesHelper
  end
end

app/helpers/dashboard/organizations_helper.rb
# frozen_string_literal: true

module Dashboard
  module OrganizationsHelper
  end
end

app/helpers/dashboard/service_areas_helper.rb
# frozen_string_literal: true

module Dashboard
  module ServiceAreasHelper
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/views/dashboard/companies/_company.html.erb
<tr id="<%= dom_id company %>">
  <td
    class="
      whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0
    "
  ><%= link_to company.name, [:dashboard, company] %></td>
  <td
    class="
      hidden whitespace-nowrap px-3 py-4 text-sm text-gray-500 sm:table-cell
    "
  ><%= company.created_at %></td>
  <td
    class="
      whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0
    "
  >
    <%= link_to edit_dashboard_company_path(company), class: "text-indigo-600 hover:text-indigo-900" do %>
      Edit<span class="sr-only">,
        <%= company.name %></span>
    <% end %>
  </td>
</tr>

app/views/dashboard/companies/_form.html.erb
<%= form_with(model: [:dashboard, company], class: "contents") do |form| %>
  <% if company.errors.any? %>
    <div
      id="error_explanation"
      class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3"
    >
      <h2><%= pluralize(company.errors.count, "error") %>
        prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name,
                    class:
                      "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class:
                  "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/dashboard/companies/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing company</h1>

  <%= render "form", company: @company %>

  <%= link_to "Show this company", [:dashboard, @company], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to companies", dashboard_companies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/dashboard/companies/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p
      class="
        py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block
      "
      id="notice"
    ><%= notice %></p>
  <% end %>

  <% content_for :title, "Companies" %>
  <div class="px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-base font-semibold text-gray-900">Companies</h1>
        <p class="mt-2 text-sm text-gray-700">A list of all the companies for
          <%= Current.user.organization.name %>.</p>
      </div>
      <% if policy(:company).create? %>
        <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
          <%= button_to "Add Company",
          new_dashboard_company_path,
          method: :get,
          class:
            "
                                                      block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold
                                                      text-white shadow-sm hover:bg-indigo-500 focus-visible:outline
                                                      focus-visible:outline-2 focus-visible:outline-offset-2
                                                      focus-visible:outline-indigo-600
                                                    " %>
        </div>
      <% end %>
    </div>
    <div class="-mx-4 mt-8 sm:-mx-0">
      <table class="min-w-full divide-y divide-gray-300">
        <thead>
          <tr>
            <th
              scope="col"
              class="
                py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0
              "
            >Name</th>
            <th
              scope="col"
              class="
                hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell
              "
            >Created At</th>
            <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
              <span class="sr-only">Edit</span>
            </th>
          </tr>
        </thead>
        <tbody id="companies" class="divide-y divide-gray-200 bg-white">
          <% @companies.each do |company| %>
            <%= render company %>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>

</div>

app/views/dashboard/companies/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New company</h1>

  <%= render "form", company: @company %>

  <%= link_to "Back to companies",
  dashboard_companies_path,
  class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/dashboard/companies/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p
        class="
          py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block
        "
        id="notice"
      ><%= notice %></p>
    <% end %>

    <div id="<%= dom_id @company %>">
      <p class="my-5">
        <strong class="block font-medium mb-1">Name:</strong>
        <%= @company.name %>
      </p>

    </div>

    <%= link_to "Edit this company",
    edit_dashboard_company_path(@company),
    class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to companies",
    dashboard_companies_path,
    class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this company",
      [:dashboard, @company],
      method: :delete,
      class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>