config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies, only: :show do
    resources :rides
    resource :customer_sign_up, path: "customers", only: %i[create new]
    resource :session
  end
  namespace :dashboard do
    resources :employees
    resources :companies
      resources :service_areas
      resources :rides
  end
  namespace :admin do
    resources :organizations
  end
  get "dashboard/index"
  resource :session
  resource :sign_up
  resources :passwords, param: :token
  resources :customers, only: :show
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard/companies#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  include Caber::Object

  belongs_to :organization
  has_many :company_employees, dependent: :destroy, inverse_of: :company
  has_many :employees, -> { select("employees.*, company_employees.role as role") }, through: :company_employees
end

app/models/company_employee.rb
# frozen_string_literal: true

class CompanyEmployee < ApplicationRecord
  belongs_to :company, inverse_of: :company_employees
  belongs_to :employee, inverse_of: :company_employees

  enum :role, { driver: 0, customer_support: 1, manager: 2, admin: 3, owner: 4 }
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :session
  attribute :company
  attribute :organization
  delegate :user, to: :session, allow_nil: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  include Authenticateable
  include Caber::Subject
  include Caber::Object

  belongs_to :company
  has_many :rides, dependent: :nullify
  # has_one :acquisition_area, -> { rides.completed.first.service_area }
  # has_one :acquisition_company, -> { rides.completed.first.company }
end

app/models/dashboard.rb
# frozen_string_literal: true

module Dashboard
  def self.table_name_prefix
    "dashboard_"
  end
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  include Authenticateable
  include Caber::Subject
  include Caber::Object

  has_many :company_employees, dependent: :destroy, inverse_of: :employee
  has_many :companies, -> { select("companies.*, company_employees.role as role") }, through: :company_employees
  has_many :rides, inverse_of: :driver, dependent: :nullify

  accepts_nested_attributes_for :company_employees, allow_destroy: true

  def not_associated_companies
    if user.nil?
      Current.organization.companies
    else
      user.organization.companies.where.not(id: companies.pluck(:id))
    end
  end
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  include Caber::Object
  has_many :companies
end

app/models/ride.rb
# frozen_string_literal: true

class Ride < ApplicationRecord
  belongs_to :customer
  belongs_to :company
  belongs_to :driver, class_name: "Employee", optional: true
end

app/models/service_area.rb
# frozen_string_literal: true

class ServiceArea < ApplicationRecord
  belongs_to :company

  enum :status, { inactive: 0, active: 1 }
end

app/models/session.rb
# frozen_string_literal: true

class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  belongs_to :organization

  delegated_type :authenticateable, types: %w[Employee Customer]
  validates_associated :authenticateable
  accepts_nested_attributes_for :authenticateable

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/rides_controller.rb
# frozen_string_literal: true

class RidesController < ApplicationController
  before_action :set_ride, only: %i[ show edit update destroy ]

  # GET /rides or /rides.json
  def index
    @rides = Current.user.authenticateable.rides.where(company_id: @company.id)
  end

  # GET /rides/1 or /rides/1.json
  def show; end

  # GET /rides/new
  def new
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit; end

  # POST /rides or /rides.json
  def create
    @ride = Ride.new(ride_params)
    @ride.company = @company
    @ride.customer = Current.user.authenticateable

    respond_to do |format|
      if @ride.save
        format.html { redirect_to [ @company, @ride ], notice: "Ride was successfully created." }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1 or /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to [ @company, @ride ], notice: "Ride was successfully updated." }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1 or /rides/1.json
  def destroy
    @ride.destroy!

    respond_to do |format|
      format.html do
 redirect_to company_rides_path(@company), status: :see_other, notice: "Ride was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

    def set_ride
      @ride = Ride.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def ride_params
      params.expect(ride: %i[
                      origin_address origin_coordinate
                      destination_address destination_coordinate
                    ]).tap do |p|
        p[:origin_coordinate] = RGeo::GeoJSON.decode(p[:origin_coordinate])
        p[:destination_coordinate] = RGeo::GeoJSON.decode(p[:destination_coordinate])
        p[:estimates] = {}
      end
    end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/rides_helper.rb
# frozen_string_literal: true

module RidesHelper
end

app/helpers/sign_ups_helper.rb
# frozen_string_literal: true

module SignUpsHelper
end

app/views/rides/_form.html.erb
<section class="h-[calc(100vh-6rem)]" aria-labelledby="section-1-title">
  <div class="h-full overflow-hidden rounded-lg bg-white shadow ">
    <%= form_with(model: [@company, ride], class: "contents") do |form| %>
      <% if ride.errors.any? %>
        <div
          id="error_explanation"
          class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3"
        >
          <h2><%= pluralize(ride.errors.count, "error") %>
            prohibited this ride from being saved:</h2>

          <ul class="list-disc ml-6">
            <% ride.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="p-6 h-full flex flex-col items-center gap-4">
        <div data-controller="create-ride" class="w-full h-[calc(100%-3rem)]">
          <div data-create-ride-target="map" class="w-full h-full rounded"></div>
        </div>
        <div class="inline">
          <%= form.submit class:
                        "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/rides/_ride.html.erb
<div id="<%= dom_id ride %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Customer:</strong>
    <%= ride.customer_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Company:</strong>
    <%= ride.company_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Driver:</strong>
    <%= ride.driver_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Queried at:</strong>
    <%= ride.created_at %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Requested at:</strong>
    <%= ride.requested_at %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Canceled at:</strong>
    <%= ride.canceled_at %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Picked up at:</strong>
    <%= ride.picked_up_at %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Completed at:</strong>
    <%= ride.completed_at %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Origin address:</strong>
    <%= ride.origin_address %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Origin coordinate:</strong>
    <%= ride.origin_coordinate %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Destination address:</strong>
    <%= ride.destination_address %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Destination coordinate:</strong>
    <%= ride.destination_coordinate %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Estimates:</strong>
    <%= ride.estimates %>
  </p>
</div>

app/views/rides/edit.html.erb
<% content_for :title, "Editing ride" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing ride</h1>

  <%= render "form", ride: @ride %>

  <%= link_to "Show this ride", @ride, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to rides", rides_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/rides/index.html.erb
<% content_for :title, "Rides" %>

<div class="w-full">
  <% if notice.present? %>
    <p
      class="
        py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block
      "
      id="notice"
    ><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Rides</h1>
    <%= link_to "New ride",
    @company,
    class:
      "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="rides" class="min-w-full">
    <% if @rides.any? %>
      <% @rides.each do |ride| %>
        <%= render ride %>
        <p>
          <%= link_to "Show this ride",
          [@company, ride],
          class:
            "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No rides found.</p>
    <% end %>
  </div>
</div>

app/views/rides/new.html.erb
<% content_for :title, "Request ride" %>

<div class="md:w-2/3 w-full">

  <%= render "form", ride: @ride %>

  <%= link_to "Back to rides",
  company_rides_path(@company),
  class:
    "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/rides/show.html.erb
<% content_for :title, "Showing ride" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p
      class="
        py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block
      "
      id="notice"
    ><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing ride</h1>

  <%= render @ride %>

  <%= link_to "Edit this ride",
  edit_company_ride_path(@company, @ride),
  class:
    "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to rides",
  company_rides_path(@company),
  class:
    "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this ride",
    [@company, @ride],
    method: :delete,
    class:
      "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>